### ISSUE TITLE
Remove version header warning for listed media types

### ISSUE THREAD

**Issue by Lakitna** [rabobank/openapi-contract-validator#4]
Add an entry in the config. Something like below.

This also gives us an opportunity to introduce versioning strategies. The Zalando strategy (content-type header versioning) is default.

```yaml
versioning:
  location: 'content-type'
  disableOnContentType:
    - application/problem+json
    - ...
```

Depends on #3 being done
